LinkDev.CompanySuite.PL/Controllers/DepartmentController.cs
using LinkDev.CompanyBase.DAL.Models.Departments;
using LinkDev.CompanyBase.PL.ViewModels.Departments;
using LinkDev.CompanyBase.BLL.Moduls.DTO;
using LinkDev.CompanyBase.BLL.Moduls.DTO.Departments;
using LinkDev.CompanyBase.BLL.Services.Departments;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using AutoMapper;

namespace LinkDev.CompanyBase.PL.Controllers
{
    public class DepartmentController : Controller
    {

        #region Services

        private readonly IDepartmentService _departmentService;
        private readonly ILogger<DepartmentController> _logger;
        private readonly IWebHostEnvironment _environment;
        private readonly IMapper _mapper;

        public DepartmentController(IDepartmentService departmentService, ILogger<DepartmentController> logger, IWebHostEnvironment environment , IMapper Mapper)
        {
            _departmentService = departmentService;
            _logger = logger;
            _environment = environment;
            _mapper = Mapper;
        }

        #endregion

        #region Index

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var departments = await _departmentService.GetAllDepartmentsAsync();

            return View(departments);
        }
        #endregion

        #region Create

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DepartmentViewModel departmentVM)
        {

            if (!ModelState.IsValid)
                return View(departmentVM);
            var message = string.Empty;
            try
            {
                var CreatedDepartment = _mapper.Map<CreatedDepartmentDto>(departmentVM);

                var created = await _departmentService.CreateDepartmentAsync(CreatedDepartment) > 0;


                if (created)
                
                    TempData["Message"] = "Department has been created successfully";

                else
                
                    TempData["Message"] = "Department has not been created successfully";
                
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);

                message = _environment.IsDevelopment() ? ex.Message : "Department is not created";

            }

            ModelState.AddModelError(string.Empty, message);
            return View(departmentVM);



        }

        #endregion

        #region Details 

        public async  Task<IActionResult> Details(int? id)
        {
            if (id is null)
                return BadRequest();

            var department = await _departmentService.GetDepByIdAsync(id.Value);

            if (department is null)
                return NotFound();

            return View(department);
        }
        #endregion

        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return BadRequest();

            var department = await _departmentService.GetDepByIdAsync(id.Value);

            if (department is null)
                return NotFound();

            var departmentVM = _mapper.Map<DepartmentDetailsDto, DepartmentViewModel>(department);

          return View(departmentVM);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, DepartmentViewModel departmentVM)
        {
            if (!ModelState.IsValid)
                return View(departmentVM);
            var message = string.Empty;
            try
            {
                var departmentToUpdate = _mapper.Map<UpdatedDepartmentDto>(departmentVM);
                var Updated = await _departmentService.UpdateDepartmentAsync(departmentToUpdate) > 0;

                if (Updated)
                    return RedirectToAction(nameof(Index));

                message = "Department is not updated";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);

                message = _environment.IsDevelopment() ? ex.Message : "Department is not updated";

            }

            ModelState.AddModelError(string.Empty, message);
            return View(departmentVM);
        }
        #endregion

        #region Delete

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id is null)
                return BadRequest();

            var department = _departmentService.GetDepByIdAsync(id.Value);

            if (department is null)
                return NotFound();
            return View(department);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var message = string.Empty;

            try
            {
                var deleted =await _departmentService.DeleteDepartmentAsync(id);

                if (deleted)
                    return RedirectToAction(nameof(Index));


                message = "The department has not been deleted";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);

                message = _environment.IsDevelopment() ? ex.Message : "Department is not updated";

            }

            //ModelState.AddModelError(string.Empty, message);
            return RedirectToAction(nameof(Index));

        } 
        #endregion


    }
}

LinkDev.CompanySuite.PL/Controllers/EmployeeController.cs
using LinkDev.CompanyBase.BLL.Moduls.DTO.Employees;
using LinkDev.CompanyBase.BLL.Services.Departments;
using LinkDev.CompanyBase.BLL.Services.Employees;
using LinkDev.CompanyBase.PL.ViewModels.Employees;
using Microsoft.AspNetCore.Mvc;

namespace LinkDev.CompanyBase.PL.Controllers
{
    public class EmployeeController : Controller
    {

        #region Services

        private readonly IEmployeeService _employeeService;
        private readonly ILogger<EmployeeController> _loger;
        private readonly IWebHostEnvironment _environment;
        private readonly IDepartmentService? _departmentService;

        public EmployeeController(IEmployeeService employeeService, ILogger<EmployeeController> loger, IWebHostEnvironment environment)
        {
            _employeeService = employeeService;
            _loger = loger;
            _environment = environment;
            
        }
        #endregion

        #region Index

        [HttpGet]
        public async Task<IActionResult> Index(string search)
        {
            var employees = await _employeeService.GetEmployeesAsync(search);

            return View(employees);
        }
        #endregion

        #region Create

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewmodel employeeVM)
        {

            if (!ModelState.IsValid)
                return View(employeeVM);
            var message = string.Empty;
            try
            {

                var CreatedEmp = new CreatedEmployeeDto()
                {
                    Name = employeeVM.Name,
                    Age = employeeVM.Age,
                    Email = employeeVM.Email,
                    Address = employeeVM.Address,
                    Salary = employeeVM.Salary,
                    PhoneNumber = employeeVM.PhoneNumber,
                    Gender = employeeVM.Gender,
                    EmployeeType = employeeVM.EmployeeType,
                    IsActive = employeeVM.IsActive,
                    DepartmentId= employeeVM.DepartmentId,
                    Img = employeeVM.Img


                };


                var result = await _employeeService.CreateEmployeeAsync(CreatedEmp);
                if (result > 0)
                    return RedirectToAction(nameof(Index));
                else
                {

                    message = "employee is not created";
                    ModelState.AddModelError(string.Empty, message);
                }
                return View(employeeVM);
            }
            catch (Exception ex)
            {
                _loger.LogError(ex, ex.Message);

                message = _environment.IsDevelopment() ? ex.Message : "Employee is not created";

            }

            ModelState.AddModelError(string.Empty, message);
            return View(employeeVM);



        }

        #endregion

        #region Details 

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
                return BadRequest();

            var employee = await _employeeService.GetEmpByIdAsync(id.Value);

            if (employee is null)
                return NotFound();

            return View(employee);
        }
        #endregion

        #region Update
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
          
            if (id is null)
                return BadRequest();

            var employee = await _employeeService.GetEmpByIdAsync(id.Value);

            if (employee is null)
                return NotFound();

           
            return View(new EmployeeViewmodel()
            {
                Name = employee.Name,
                Age = employee.Age,
                Email = employee.Email,
                Address = employee.Address,
                Salary = employee.Salary,
                PhoneNumber = employee.PhoneNumber,
                Gender = employee.Gender,
                EmployeeType = employee.EmployeeType,
                IsActive = employee.IsActive,
                HiringDate = employee.HiringDate,

            });

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, EmployeeViewmodel employeeVM)
        {
            if (!ModelState.IsValid)
                return View(employeeVM);
            var message = string.Empty;
            try
            {
                var UpdatedEmp = new UpdatedEmployeeDto()
                {
                    Id = id,
                    Name = employeeVM.Name,
                    Age = employeeVM.Age,
                    Email = employeeVM.Email,
                    Address = employeeVM.Address,
                    Salary = employeeVM.Salary,
                    PhoneNumber = employeeVM.PhoneNumber,
                    Gender = employeeVM.Gender,
                    EmployeeType = employeeVM.EmployeeType,
                    IsActive = employeeVM.IsActive,



                };

                var Updated =await _employeeService.UpdateEmpAsync(UpdatedEmp) > 0;

                if (Updated)
                    return RedirectToAction(nameof(Index));

                message = "employee is not updated";
            }
            catch (Exception ex)
            {
                _loger.LogError(ex, ex.Message);

                message = _environment.IsDevelopment() ? ex.Message : "employee is not updated";

            }

            ModelState.AddModelError(string.Empty, message);
            return View(employeeVM);
        }
        #endregion

       #region Delete

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
                return BadRequest();

            var employee = await _employeeService.GetEmpByIdAsync(id.Value);

            if (employee is null)
                return NotFound();
            return View(employee);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var message = string.Empty;

            try
            {
                var deleted = await _employeeService.DeleteEmpAsync(id);

                if (deleted)
                    return RedirectToAction(nameof(Index));


                message = "The employee has not been deleted";
            }
            catch (Exception ex)
            {
                _loger.LogError(ex, ex.Message);

                message = _environment.IsDevelopment() ? ex.Message : "employee is not updated";

            }

            //ModelState.AddModelError(string.Empty, message);
            return RedirectToAction(nameof(Index));

        }
        #endregion

    }
}

LinkDev.CompanySuite.PL/Views/Shared/AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>@ViewData["Title"]</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/AuthLayout.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>@ViewData["Title"]</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("ValidationScripts", required: false)
</body>
</html>

LinkDev.CompanySuite.PL/Views/Shared/_ButtonsPartial.cshtml
@model int

<td>
    <a  asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fa-sharp-duotone fa-solid fa-eye"></i>Details
    </a>
</td>
<td>
    <a  asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fa-duotone fa-solid fa-pen-to-square"></i>Update
    </a>
</td>
<td>
  @*   <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-trash"></i>
    </a> *@

    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#DeleteModal">
        <i class="fa-duotone fa-solid fa-pen-to-square"></i> Delete
    </button>
</td>

LinkDev.CompanySuite.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompanyBase</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LinkDev.CompanySuite.PL.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow ms-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CompanyBase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted fixed-bottom p-3 text-center">
        <div class="container">

            &copy; 2024 - CompanyBase - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScripts", required: false)
</body>
</html>